ECHO OFF
rd /s /q %temp%\output
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250
"ostress.exe" -E -S.\ -dEcom -Q"exec Ecom.dbo.spInserePedido" -mstress -quiet -n100 -r250