SELECT @@SERVERNAME as ServidorAzure, DB_NAME() as DatabaseName,
TABLE_NAME,COLUMN_NAME,DATA_TYPE,CHARACTER_MAXIMUM_LENGTH,TABLE_SCHEMA
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME  = 'previdencia_pre_implantacao_is'
and TABLE_SCHEMA = 'casadocorretor'