SELECT TOP 10
	TOTAL_LOGICAL_READS,
	TOTAL_LOGICAL_WRITES,
	EXECUTION_COUNT,
	TOTAL_LOGICAL_READS+TOTAL_LOGICAL_WRITES AS [IO_TOTAL],
	QT.TEXT AS QUERY_TEXT,
	DB_NAME(QT.DBID) AS DATABASE_NAME,
	QT.OBJECTID AS OBJECT_ID
FROM SYS.DM_EXEC_QUERY_STATS QS
CROSS APPLY SYS.DM_EXEC_SQL_TEXT(SQL_HANDLE) QT
WHERE TOTAL_LOGICAL_READS+TOTAL_LOGICAL_WRITES > 0
ORDER BY [IO_TOTAL] DESC