SELECT 
	QS.EXECUTION_COUNT,
	QT.TEXT AS QUERY_TEXT,
	QT.DBID,
	DBNAME= DB_NAME (QT.DBID),
	QT.OBJECTID,
	QS.TOTAL_ROWS,
	QS.LAST_ROWS,
	QS.MIN_ROWS,
	QS.MAX_ROWS
FROM SYS.DM_EXEC_QUERY_STATS AS QS
CROSS APPLY SYS.DM_EXEC_SQL_TEXT(QS.SQL_HANDLE) AS QT
ORDER BY QS.EXECUTION_COUNT DESC